# Generated by Django 5.1 on 2024-08-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('german_sentence', models.TextField()),
                ('hungarian_sentence', models.TextField()),
                ('i_knew_counter', models.IntegerField()),
                ('did_not_knew_counter', models.IntegerField()),
            ],
        ),
    ]
